pub mod interpretter;
use interpretter::*;
pub mod scope;
use scope::*;
pub mod value_variant;
use value_variant::*;
pub mod tokens;
use tokens::*;
pub mod lexer;
use lexer::*;
pub mod heap;
use heap::*;